branches:
  only:
    - master
    - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

deploy:
  user: rafaelpivato
  provider: pypi
  password:
    secure: VC5ADulLBrSYqvgY8fy7d28j0VbX6goSJpHdHg3MJH1jTo4K1KEIHe79lrY34RbWt9meNw1KVi4q32tf4B85nb/P6/5qcJVIQGI4O3JBAG2fg61jclgAeQKESg4Klbx8nb538JAUiR8YibsqJ634IUyxmtJDRhLeHmhPAyU+nax0mPS1Gtat9y1RIGVG6lwMKQrhe5WGVAbxnITJAYPWMatZEbsRrQIOyfi7oNxrSdN3VMU3ISjHGvoHlSD96IM+OI5bHds+bdg7wyjKg+CN4hPezp4+EitgGm8ubJ6qdRS7+Dc171bhGfwZMBRJPCqLtnRin9lwIDOS9eoONiNoZLghTx0KqMcrgSPT1mRVHrH+neEmFUjVuzHzrWz5/A9IU6iQj+7QKhJuQsKLAD79PNfFNmkqysLolOk6kNSGmaCQ9B4U8aZDUcxrAxg0iaZ3s/vAmUNoxvEnKO0pE9oLnoZHvtp2rtjIBINai7pITuPjcjgUmmICMFgawUNDBLefJmkBhPe4w66CXUnnzjIcdvMahvKK+5/bzNjOvB+FdulSmgS+wDds0rMb19mZvo7/WstEVlmxQ3AGeXT/jYMVPTA4dC1w9Ps8ZojT+RXgQ7/+wkVaRl8+pVVvxadF5B46LTghqI1WiQAJNszkf5VPSyCXcaSTCaBj03xlTuIBzIc=
  distributions: sdist bdist_wheel
  on:
    repo: pyupio/changelogs
    tags: true
    python: "3.6"

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install tox-travis
  - pip install codecov
  - pip install flake8
script:
  - tox
after_success:
  - codecov
  - flake8
